### ISSUE TITLE
Add documentation on how to test/use this in godot 4.0

### ISSUE THREAD

**Issue by julianhenrywilson** [GarbajYT/godot_updated_fps_controller#2]
In its current state just dropping the files into a project and messing around does not work and Im failing to find instructions on how test this out.

**Comment by TaylorBradshaw** [comment]
In order to make use of this project you will need an existing project with stuff to move around on -- you can then copy paste either folder from this project (4.0 or 3.3) into your own project (do this in the Window's file explorer/linux equivalent to avoid issues), and then drag the "FPS.tscn" from that folder into your main scene (in Godot).  You will also need to add the input actions to your input map ("move_forward", "move_backward", "move_left", "move_right", "jump") and then you should have working movement.

I think adding the "project.godot" file and a demo scene to this project would be a good idea though, considering people are most likely coming here from tutorials.

**Comment by GarbajYT** [comment]
I will look into adding a demo scene to test out the controller
